# These are supported funding model platforms

github: [sh1tters, mikkelcoder]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
