# Download CLIENT Rest from VS code to use this file

POST http://localhost:8000/v1/auth/relay/handshake
Content-Type: application/json

{
    "name": "relay_0001",
    "password": "123"
}

###

POST http://localhost:8000/v1/auth/relay/new_drone
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZWxheV8wMDAxIiwiZXhwIjoxNjgwNzE1NTY3fQ.8czvoi1d3tRXcHZRoJQAYM-tsc6Dics5KifxlDLDJG0
Content-Type: application/json

{
    "name": "drone_01",
    "parent": "relay_0001"
}
