# Download CLIENT Rest from VS code to use this file

POST http://localhost:8000/v1/auth/relay/handshake
Content-Type: application/json

{
    "name": "relay_0001",
    "password": "123"
}

###

POST http://localhost:8000/v1/auth/relay/new_drone
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZWxheV8wMDAxIiwiZXhwIjoxNjgwNzE3MzU1fQ.nW5-H1UbmqkER0FsEOZs6rlf2LNbfz3reD7q49kXi5U
Content-Type: application/json

{
    "name": "drone_01",
    "parent": "relay_0001"
}

###

POST http://localhost:8000/v1/auth/relay/drones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZWxheV8wMDAxIiwiZXhwIjoxNjgwNzE3MzY4fQ.PnsU8Gkd8sYj5EHgCZqvje5lOpnQMxjvQxRwiOCZDEM
Content-Type: application/json

{
    "name": "relay_0001"
}