# Download CLIENT Rest from VS code to use this file

POST http://localhost:8000/v1/auth/login
Content-Type: application/json

{
    "name": "admin",
    "password": "123"
}

###

GET http://localhost:8000/v1/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MDM1MTcxM30.28IdoEFVUCYYjBpycwuyNxTW3uQQD3nnWMGNTb2yAsw

###

GET http://localhost:8000/

###

POST http://localhost:8000/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MDM1MTYyOX0.uEJMorAeBdQbxUxMJsCGf6Z74JBWBAJ-zoEk0WK3P5A


###

POST http://localhost:8000/v1/auth/login/relay
Content-Type: application/json

{
    "id": 554,
    "key": "nigga"
}