# Download CLIENT Rest from VS code to use this file

POST http://localhost:8000/v1/auth/login
Content-Type: application/json

{
    "name": "admin",
    "password": "123"
}

###

GET http://localhost:8000/v1/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MDM1MTEzNH0.XwX1uBqqZ_26TK3xVWdLisNa_TBA_m9m49jabCdgzps

###

GET http://localhost:8000/

###

POST http://localhost:8000/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY3OTY1MTkxM30.fMYzqjXfoRym4Br9papkJyTSBGHuwFeX6wDh5Xp3-g8
