# Download CLIENT Rest from VS code to use this file

POST http://localhost:8000/v1/api/frontend/login
Content-Type: application/json

{
    "name": "admin",
    "password": "123"
}

###

GET http://localhost:8000/v1/api/frontend/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MDc5NzIyN30.YppaXTGlwcQ26sSNrtlfl_qThOUPbSbr46imVYKnqbY

###

POST http://localhost:8000/v1/api/frontend/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MDM1MTYyOX0.uEJMorAeBdQbxUxMJsCGf6Z74JBWBAJ-zoEk0WK3P5A

###

POST http://localhost:8000/v1/api/frontend/new_cmd_for_drone
Content-Type: application/json

{
    "relay_name": "relay_0001",
    "drone_name": "drone_02",
    "cmd": "[dawdw, dawdw, dwad]"
}

###

GET http://localhost:8000/v1/api/frontend/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MjY3MDcxOH0.C8s3DK5DEsyV1apO464KFBlNOdGsnERHsOoCp1PCyCM


###
POST http://localhost:8000/v1/api/frontend/drone/takeoff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MjY3MDcxOH0.C8s3DK5DEsyV1apO464KFBlNOdGsnERHsOoCp1PCyCM
Content-Type: application/json

{
    "name": "drone_001",
    "parent": "relay_0001"
}