# Download CLIENT Rest from VS code to use this file

POST http://localhost:8000/v1/api/frontend/login
Content-Type: application/json

{
    "name": "admin",
    "password": "123"
}

###

GET http://localhost:8000/v1/api/frontend/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MzI5MDAyOX0.yXXxu02N3-sTrbM8BiH15PcBYZWCIgQPBzh2e97e3sA

###

POST http://localhost:8000/v1/api/frontend/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MzI5MDAyOX0.yXXxu02N3-sTrbM8BiH15PcBYZWCIgQPBzh2e97e3sA

###

POST http://localhost:8000/v1/api/frontend/new_cmd_for_drone
Content-Type: application/json

{
    "relay_name": "relay_0001",
    "drone_name": "drone_02",
    "cmd": "[dawdw, dawdw, dwad]"
}

###

GET http://localhost:8000/v1/api/frontend/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MzI5MDA5MH0.GVEEclzBOZL2qaYqyw_ay9PvZFBxXlOws0RlURqub14


###
POST http://localhost:8000/v1/api/frontend/drone/takeoff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MjY3MDcxOH0.C8s3DK5DEsyV1apO464KFBlNOdGsnERHsOoCp1PCyCM
Content-Type: application/json

{
    "name": "drone_001",
    "parent": "relay_0001"
}